/*
 * generated by RMP Smart Objects Code Generator 0.1 
 */
 
var process_1 = new function() {
    
    this.button = saul.get_by_name("button");
    
    var self =  this;
    
    this.start = function () {
        var handler;
        var callback = function () {
            print("button_pressed");
            return true;
        }
        print("Waiting...");
        self.button.on_threshold(0, callback, saul.op.EQ);
    };
    
    this.activity6 = function () {
        coap.request("http://example.runmyprocess.com/object/42/alarm", "PUT", "ON");
        self.await7();
    };
}

process_1.start();
