/*
 * generated by RMP Smart Objects Code Generator 0.1 
 */
 
var process_1 = new function() {
    
    this.button = saul.get_by_name("button");
    this.led = saul.get_by_name("led");
    this.temp_sensor = saul.get_by_name("temp_sensor");

    var self =  this;
    buttonState = true;
    temp_value = 0;
    
    this.start = function () {
        //var handler;

	//Start producer
	this.producer();
    };
   

    this.consumer = function () {

        coap.request("coap://[fd00:dead:beef::1]/coap", coap.method.POST, temp_value);
        //self.await7();
    };

    this.producer = function() {

        var callback = function () {
            print("button_pressed");
            temp_value = self.temp_sensor.get_value();
	    print(temp_value);
	    this.consumer();
            return true;
        }

        print("Waiting...");
        self.button.on_threshold(0, callback, saul.op.EQ);
    }

}

process_1.start();
